### ISSUE TITLE
junk after date

### ISSUE THREAD

**Issue by ggrothendieck** [shrektan/ymd#2]
You may or may not want to implement this but just wanted to point out that `as.Date` in base R and `ymd` in lubridate both ignore junk at the end if you don't supply a format.

```
as.Date("2000-01-02junk")
## [1] "2000-01-02"

library(ymd)
ymd("2000-01-02junk")
## [1] NA
```

**Comment by shrektan** [comment]
Thanks for the reminder. It's not difficult to implement but I decide not. The reasons are:

1. Dates with junk suffix probably should be regarded as abnormal input, thus NA;
2. It's better to keep the code as simple and minimal as possible.
