### ISSUE TITLE
Unable to build on AArch64

### ISSUE THREAD

**Issue by tom91136** [shrektan/ymd#5]
On AArch64 Linux, I'm observing the same failure as https://github.com/extendr/extendr/issues/628.
I believe upgrading the extendr dependency from the pinned one (ref to https://github.com/extendr/extendr/pull/627) to https://github.com/extendr/extendr/pull/629 will resolve this as the fix was introduced in that PR.
Alternatively, we can probably use `rev = "v0.6.0"` which was released last October and appears to be stable.

**Comment by shrektan** [comment]
Thanks. PR is welcomed.

**Comment by shrektan** [comment]
it should be resolved now.
